name: englitales_data
description: Englitales upload data
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  provider: ^4.3.3
  file_picker: ^3.0.3
  pluto_grid: ^2.2.1

flutter:
  uses-material-design: true
